--- 
log_file: log/mongrel_staging.log
port: 8311
pid_file: tmp/pids/mongrel_staging.pid
servers: 1
cwd: /home/mongrel/re_staging/current
environment: production
address: 0.0.0.0
log_file: /home/mongrel/re_staging/shared/log/production.log
pid_file: /home/mongrel/re_staging/shared/pids
user: mongrel
group: mongrel
