--- 
log_file: log/mongrel.log
port: 8300
pid_file: tmp/pids/mongrel.pid
servers: 1
cwd: /home/mongrel/re/current
environment: production
address: 0.0.0.0
log_file: /home/mongrel/re/shared/log/production.log
pid_file: /home/mongrel/re/shared/pids
user: mongrel
group: mongrel
